//*
// Copyright 2025 uk
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: goto.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Input struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       string                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Input) Reset() {
	*x = Input{}
	mi := &file_goto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Input) ProtoMessage() {}

func (x *Input) ProtoReflect() protoreflect.Message {
	mi := &file_goto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Input.ProtoReflect.Descriptor instead.
func (*Input) Descriptor() ([]byte, []int) {
	return file_goto_proto_rawDescGZIP(), []int{0}
}

func (x *Input) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type StreamConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkSize     int32                  `protobuf:"varint,1,opt,name=chunkSize,proto3" json:"chunkSize,omitempty"`
	ChunkCount    int32                  `protobuf:"varint,2,opt,name=chunkCount,proto3" json:"chunkCount,omitempty"`
	Interval      string                 `protobuf:"bytes,3,opt,name=interval,proto3" json:"interval,omitempty"`
	Payload       string                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamConfig) Reset() {
	*x = StreamConfig{}
	mi := &file_goto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamConfig) ProtoMessage() {}

func (x *StreamConfig) ProtoReflect() protoreflect.Message {
	mi := &file_goto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamConfig.ProtoReflect.Descriptor instead.
func (*StreamConfig) Descriptor() ([]byte, []int) {
	return file_goto_proto_rawDescGZIP(), []int{1}
}

func (x *StreamConfig) GetChunkSize() int32 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

func (x *StreamConfig) GetChunkCount() int32 {
	if x != nil {
		return x.ChunkCount
	}
	return 0
}

func (x *StreamConfig) GetInterval() string {
	if x != nil {
		return x.Interval
	}
	return ""
}

func (x *StreamConfig) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type Output struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Payload       string                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	At            string                 `protobuf:"bytes,3,opt,name=at,proto3" json:"at,omitempty"`
	GotoHost      string                 `protobuf:"bytes,4,opt,name=gotoHost,proto3" json:"gotoHost,omitempty"`
	GotoPort      int32                  `protobuf:"varint,5,opt,name=gotoPort,proto3" json:"gotoPort,omitempty"`
	ViaGoto       string                 `protobuf:"bytes,6,opt,name=viaGoto,proto3" json:"viaGoto,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Output) Reset() {
	*x = Output{}
	mi := &file_goto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Output) ProtoMessage() {}

func (x *Output) ProtoReflect() protoreflect.Message {
	mi := &file_goto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Output.ProtoReflect.Descriptor instead.
func (*Output) Descriptor() ([]byte, []int) {
	return file_goto_proto_rawDescGZIP(), []int{2}
}

func (x *Output) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Output) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *Output) GetAt() string {
	if x != nil {
		return x.At
	}
	return ""
}

func (x *Output) GetGotoHost() string {
	if x != nil {
		return x.GotoHost
	}
	return ""
}

func (x *Output) GetGotoPort() int32 {
	if x != nil {
		return x.GotoPort
	}
	return 0
}

func (x *Output) GetViaGoto() string {
	if x != nil {
		return x.ViaGoto
	}
	return ""
}

var File_goto_proto protoreflect.FileDescriptor

const file_goto_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"goto.proto\"!\n" +
	"\x05Input\x12\x18\n" +
	"\apayload\x18\x01 \x01(\tR\apayload\"\x82\x01\n" +
	"\fStreamConfig\x12\x1c\n" +
	"\tchunkSize\x18\x01 \x01(\x05R\tchunkSize\x12\x1e\n" +
	"\n" +
	"chunkCount\x18\x02 \x01(\x05R\n" +
	"chunkCount\x12\x1a\n" +
	"\binterval\x18\x03 \x01(\tR\binterval\x12\x18\n" +
	"\apayload\x18\x04 \x01(\tR\apayload\"\x94\x01\n" +
	"\x06Output\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload\x12\x0e\n" +
	"\x02at\x18\x03 \x01(\tR\x02at\x12\x1a\n" +
	"\bgotoHost\x18\x04 \x01(\tR\bgotoHost\x12\x1a\n" +
	"\bgotoPort\x18\x05 \x01(\x05R\bgotoPort\x12\x18\n" +
	"\aviaGoto\x18\x06 \x01(\tR\aviaGoto2\x98\x01\n" +
	"\x04Goto\x12\x19\n" +
	"\x04echo\x12\x06.Input\x1a\a.Output\"\x00\x12\x1f\n" +
	"\bstreamIn\x12\x06.Input\x1a\a.Output\"\x00(\x01\x12'\n" +
	"\tstreamOut\x12\r.StreamConfig\x1a\a.Output\"\x000\x01\x12+\n" +
	"\vstreamInOut\x12\r.StreamConfig\x1a\a.Output\"\x00(\x010\x012\x99\x01\n" +
	"\x05Goto2\x12\x19\n" +
	"\x04echo\x12\x06.Input\x1a\a.Output\"\x00\x12\x1f\n" +
	"\bstreamIn\x12\x06.Input\x1a\a.Output\"\x00(\x01\x12'\n" +
	"\tstreamOut\x12\r.StreamConfig\x1a\a.Output\"\x000\x01\x12+\n" +
	"\vstreamInOut\x12\r.StreamConfig\x1a\a.Output\"\x00(\x010\x012\x99\x01\n" +
	"\x05Goto3\x12\x19\n" +
	"\x04echo\x12\x06.Input\x1a\a.Output\"\x00\x12\x1f\n" +
	"\bstreamIn\x12\x06.Input\x1a\a.Output\"\x00(\x01\x12'\n" +
	"\tstreamOut\x12\r.StreamConfig\x1a\a.Output\"\x000\x01\x12+\n" +
	"\vstreamInOut\x12\r.StreamConfig\x1a\a.Output\"\x00(\x010\x01B\x06Z\x04.;pbb\x06proto3"

var (
	file_goto_proto_rawDescOnce sync.Once
	file_goto_proto_rawDescData []byte
)

func file_goto_proto_rawDescGZIP() []byte {
	file_goto_proto_rawDescOnce.Do(func() {
		file_goto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_goto_proto_rawDesc), len(file_goto_proto_rawDesc)))
	})
	return file_goto_proto_rawDescData
}

var file_goto_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_goto_proto_goTypes = []any{
	(*Input)(nil),        // 0: Input
	(*StreamConfig)(nil), // 1: StreamConfig
	(*Output)(nil),       // 2: Output
}
var file_goto_proto_depIdxs = []int32{
	0,  // 0: Goto.echo:input_type -> Input
	0,  // 1: Goto.streamIn:input_type -> Input
	1,  // 2: Goto.streamOut:input_type -> StreamConfig
	1,  // 3: Goto.streamInOut:input_type -> StreamConfig
	0,  // 4: Goto2.echo:input_type -> Input
	0,  // 5: Goto2.streamIn:input_type -> Input
	1,  // 6: Goto2.streamOut:input_type -> StreamConfig
	1,  // 7: Goto2.streamInOut:input_type -> StreamConfig
	0,  // 8: Goto3.echo:input_type -> Input
	0,  // 9: Goto3.streamIn:input_type -> Input
	1,  // 10: Goto3.streamOut:input_type -> StreamConfig
	1,  // 11: Goto3.streamInOut:input_type -> StreamConfig
	2,  // 12: Goto.echo:output_type -> Output
	2,  // 13: Goto.streamIn:output_type -> Output
	2,  // 14: Goto.streamOut:output_type -> Output
	2,  // 15: Goto.streamInOut:output_type -> Output
	2,  // 16: Goto2.echo:output_type -> Output
	2,  // 17: Goto2.streamIn:output_type -> Output
	2,  // 18: Goto2.streamOut:output_type -> Output
	2,  // 19: Goto2.streamInOut:output_type -> Output
	2,  // 20: Goto3.echo:output_type -> Output
	2,  // 21: Goto3.streamIn:output_type -> Output
	2,  // 22: Goto3.streamOut:output_type -> Output
	2,  // 23: Goto3.streamInOut:output_type -> Output
	12, // [12:24] is the sub-list for method output_type
	0,  // [0:12] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_goto_proto_init() }
func file_goto_proto_init() {
	if File_goto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_goto_proto_rawDesc), len(file_goto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_goto_proto_goTypes,
		DependencyIndexes: file_goto_proto_depIdxs,
		MessageInfos:      file_goto_proto_msgTypes,
	}.Build()
	File_goto_proto = out.File
	file_goto_proto_goTypes = nil
	file_goto_proto_depIdxs = nil
}
