//*
// Copyright 2025 uk
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: goto.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Goto_Echo_FullMethodName        = "/Goto/echo"
	Goto_StreamIn_FullMethodName    = "/Goto/streamIn"
	Goto_StreamOut_FullMethodName   = "/Goto/streamOut"
	Goto_StreamInOut_FullMethodName = "/Goto/streamInOut"
)

// GotoClient is the client API for Goto service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GotoClient interface {
	Echo(ctx context.Context, in *Input, opts ...grpc.CallOption) (*Output, error)
	StreamIn(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Input, Output], error)
	StreamOut(ctx context.Context, in *StreamConfig, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Output], error)
	StreamInOut(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamConfig, Output], error)
}

type gotoClient struct {
	cc grpc.ClientConnInterface
}

func NewGotoClient(cc grpc.ClientConnInterface) GotoClient {
	return &gotoClient{cc}
}

func (c *gotoClient) Echo(ctx context.Context, in *Input, opts ...grpc.CallOption) (*Output, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Output)
	err := c.cc.Invoke(ctx, Goto_Echo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gotoClient) StreamIn(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Input, Output], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Goto_ServiceDesc.Streams[0], Goto_StreamIn_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Input, Output]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Goto_StreamInClient = grpc.ClientStreamingClient[Input, Output]

func (c *gotoClient) StreamOut(ctx context.Context, in *StreamConfig, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Output], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Goto_ServiceDesc.Streams[1], Goto_StreamOut_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamConfig, Output]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Goto_StreamOutClient = grpc.ServerStreamingClient[Output]

func (c *gotoClient) StreamInOut(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamConfig, Output], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Goto_ServiceDesc.Streams[2], Goto_StreamInOut_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamConfig, Output]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Goto_StreamInOutClient = grpc.BidiStreamingClient[StreamConfig, Output]

// GotoServer is the server API for Goto service.
// All implementations must embed UnimplementedGotoServer
// for forward compatibility.
type GotoServer interface {
	Echo(context.Context, *Input) (*Output, error)
	StreamIn(grpc.ClientStreamingServer[Input, Output]) error
	StreamOut(*StreamConfig, grpc.ServerStreamingServer[Output]) error
	StreamInOut(grpc.BidiStreamingServer[StreamConfig, Output]) error
	mustEmbedUnimplementedGotoServer()
}

// UnimplementedGotoServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGotoServer struct{}

func (UnimplementedGotoServer) Echo(context.Context, *Input) (*Output, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Echo not implemented")
}
func (UnimplementedGotoServer) StreamIn(grpc.ClientStreamingServer[Input, Output]) error {
	return status.Errorf(codes.Unimplemented, "method StreamIn not implemented")
}
func (UnimplementedGotoServer) StreamOut(*StreamConfig, grpc.ServerStreamingServer[Output]) error {
	return status.Errorf(codes.Unimplemented, "method StreamOut not implemented")
}
func (UnimplementedGotoServer) StreamInOut(grpc.BidiStreamingServer[StreamConfig, Output]) error {
	return status.Errorf(codes.Unimplemented, "method StreamInOut not implemented")
}
func (UnimplementedGotoServer) mustEmbedUnimplementedGotoServer() {}
func (UnimplementedGotoServer) testEmbeddedByValue()              {}

// UnsafeGotoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GotoServer will
// result in compilation errors.
type UnsafeGotoServer interface {
	mustEmbedUnimplementedGotoServer()
}

func RegisterGotoServer(s grpc.ServiceRegistrar, srv GotoServer) {
	// If the following call pancis, it indicates UnimplementedGotoServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Goto_ServiceDesc, srv)
}

func _Goto_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Input)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GotoServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Goto_Echo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GotoServer).Echo(ctx, req.(*Input))
	}
	return interceptor(ctx, in, info, handler)
}

func _Goto_StreamIn_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GotoServer).StreamIn(&grpc.GenericServerStream[Input, Output]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Goto_StreamInServer = grpc.ClientStreamingServer[Input, Output]

func _Goto_StreamOut_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamConfig)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GotoServer).StreamOut(m, &grpc.GenericServerStream[StreamConfig, Output]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Goto_StreamOutServer = grpc.ServerStreamingServer[Output]

func _Goto_StreamInOut_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GotoServer).StreamInOut(&grpc.GenericServerStream[StreamConfig, Output]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Goto_StreamInOutServer = grpc.BidiStreamingServer[StreamConfig, Output]

// Goto_ServiceDesc is the grpc.ServiceDesc for Goto service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Goto_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Goto",
	HandlerType: (*GotoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "echo",
			Handler:    _Goto_Echo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "streamIn",
			Handler:       _Goto_StreamIn_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "streamOut",
			Handler:       _Goto_StreamOut_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "streamInOut",
			Handler:       _Goto_StreamInOut_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "goto.proto",
}

const (
	Goto2_Echo_FullMethodName        = "/Goto2/echo"
	Goto2_StreamIn_FullMethodName    = "/Goto2/streamIn"
	Goto2_StreamOut_FullMethodName   = "/Goto2/streamOut"
	Goto2_StreamInOut_FullMethodName = "/Goto2/streamInOut"
)

// Goto2Client is the client API for Goto2 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Goto2Client interface {
	Echo(ctx context.Context, in *Input, opts ...grpc.CallOption) (*Output, error)
	StreamIn(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Input, Output], error)
	StreamOut(ctx context.Context, in *StreamConfig, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Output], error)
	StreamInOut(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamConfig, Output], error)
}

type goto2Client struct {
	cc grpc.ClientConnInterface
}

func NewGoto2Client(cc grpc.ClientConnInterface) Goto2Client {
	return &goto2Client{cc}
}

func (c *goto2Client) Echo(ctx context.Context, in *Input, opts ...grpc.CallOption) (*Output, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Output)
	err := c.cc.Invoke(ctx, Goto2_Echo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goto2Client) StreamIn(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Input, Output], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Goto2_ServiceDesc.Streams[0], Goto2_StreamIn_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Input, Output]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Goto2_StreamInClient = grpc.ClientStreamingClient[Input, Output]

func (c *goto2Client) StreamOut(ctx context.Context, in *StreamConfig, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Output], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Goto2_ServiceDesc.Streams[1], Goto2_StreamOut_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamConfig, Output]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Goto2_StreamOutClient = grpc.ServerStreamingClient[Output]

func (c *goto2Client) StreamInOut(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamConfig, Output], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Goto2_ServiceDesc.Streams[2], Goto2_StreamInOut_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamConfig, Output]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Goto2_StreamInOutClient = grpc.BidiStreamingClient[StreamConfig, Output]

// Goto2Server is the server API for Goto2 service.
// All implementations must embed UnimplementedGoto2Server
// for forward compatibility.
type Goto2Server interface {
	Echo(context.Context, *Input) (*Output, error)
	StreamIn(grpc.ClientStreamingServer[Input, Output]) error
	StreamOut(*StreamConfig, grpc.ServerStreamingServer[Output]) error
	StreamInOut(grpc.BidiStreamingServer[StreamConfig, Output]) error
	mustEmbedUnimplementedGoto2Server()
}

// UnimplementedGoto2Server must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGoto2Server struct{}

func (UnimplementedGoto2Server) Echo(context.Context, *Input) (*Output, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Echo not implemented")
}
func (UnimplementedGoto2Server) StreamIn(grpc.ClientStreamingServer[Input, Output]) error {
	return status.Errorf(codes.Unimplemented, "method StreamIn not implemented")
}
func (UnimplementedGoto2Server) StreamOut(*StreamConfig, grpc.ServerStreamingServer[Output]) error {
	return status.Errorf(codes.Unimplemented, "method StreamOut not implemented")
}
func (UnimplementedGoto2Server) StreamInOut(grpc.BidiStreamingServer[StreamConfig, Output]) error {
	return status.Errorf(codes.Unimplemented, "method StreamInOut not implemented")
}
func (UnimplementedGoto2Server) mustEmbedUnimplementedGoto2Server() {}
func (UnimplementedGoto2Server) testEmbeddedByValue()               {}

// UnsafeGoto2Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Goto2Server will
// result in compilation errors.
type UnsafeGoto2Server interface {
	mustEmbedUnimplementedGoto2Server()
}

func RegisterGoto2Server(s grpc.ServiceRegistrar, srv Goto2Server) {
	// If the following call pancis, it indicates UnimplementedGoto2Server was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Goto2_ServiceDesc, srv)
}

func _Goto2_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Input)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Goto2Server).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Goto2_Echo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Goto2Server).Echo(ctx, req.(*Input))
	}
	return interceptor(ctx, in, info, handler)
}

func _Goto2_StreamIn_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(Goto2Server).StreamIn(&grpc.GenericServerStream[Input, Output]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Goto2_StreamInServer = grpc.ClientStreamingServer[Input, Output]

func _Goto2_StreamOut_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamConfig)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(Goto2Server).StreamOut(m, &grpc.GenericServerStream[StreamConfig, Output]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Goto2_StreamOutServer = grpc.ServerStreamingServer[Output]

func _Goto2_StreamInOut_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(Goto2Server).StreamInOut(&grpc.GenericServerStream[StreamConfig, Output]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Goto2_StreamInOutServer = grpc.BidiStreamingServer[StreamConfig, Output]

// Goto2_ServiceDesc is the grpc.ServiceDesc for Goto2 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Goto2_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Goto2",
	HandlerType: (*Goto2Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "echo",
			Handler:    _Goto2_Echo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "streamIn",
			Handler:       _Goto2_StreamIn_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "streamOut",
			Handler:       _Goto2_StreamOut_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "streamInOut",
			Handler:       _Goto2_StreamInOut_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "goto.proto",
}

const (
	Goto3_Echo_FullMethodName        = "/Goto3/echo"
	Goto3_StreamIn_FullMethodName    = "/Goto3/streamIn"
	Goto3_StreamOut_FullMethodName   = "/Goto3/streamOut"
	Goto3_StreamInOut_FullMethodName = "/Goto3/streamInOut"
)

// Goto3Client is the client API for Goto3 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Goto3Client interface {
	Echo(ctx context.Context, in *Input, opts ...grpc.CallOption) (*Output, error)
	StreamIn(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Input, Output], error)
	StreamOut(ctx context.Context, in *StreamConfig, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Output], error)
	StreamInOut(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamConfig, Output], error)
}

type goto3Client struct {
	cc grpc.ClientConnInterface
}

func NewGoto3Client(cc grpc.ClientConnInterface) Goto3Client {
	return &goto3Client{cc}
}

func (c *goto3Client) Echo(ctx context.Context, in *Input, opts ...grpc.CallOption) (*Output, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Output)
	err := c.cc.Invoke(ctx, Goto3_Echo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goto3Client) StreamIn(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Input, Output], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Goto3_ServiceDesc.Streams[0], Goto3_StreamIn_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Input, Output]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Goto3_StreamInClient = grpc.ClientStreamingClient[Input, Output]

func (c *goto3Client) StreamOut(ctx context.Context, in *StreamConfig, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Output], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Goto3_ServiceDesc.Streams[1], Goto3_StreamOut_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamConfig, Output]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Goto3_StreamOutClient = grpc.ServerStreamingClient[Output]

func (c *goto3Client) StreamInOut(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamConfig, Output], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Goto3_ServiceDesc.Streams[2], Goto3_StreamInOut_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamConfig, Output]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Goto3_StreamInOutClient = grpc.BidiStreamingClient[StreamConfig, Output]

// Goto3Server is the server API for Goto3 service.
// All implementations must embed UnimplementedGoto3Server
// for forward compatibility.
type Goto3Server interface {
	Echo(context.Context, *Input) (*Output, error)
	StreamIn(grpc.ClientStreamingServer[Input, Output]) error
	StreamOut(*StreamConfig, grpc.ServerStreamingServer[Output]) error
	StreamInOut(grpc.BidiStreamingServer[StreamConfig, Output]) error
	mustEmbedUnimplementedGoto3Server()
}

// UnimplementedGoto3Server must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGoto3Server struct{}

func (UnimplementedGoto3Server) Echo(context.Context, *Input) (*Output, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Echo not implemented")
}
func (UnimplementedGoto3Server) StreamIn(grpc.ClientStreamingServer[Input, Output]) error {
	return status.Errorf(codes.Unimplemented, "method StreamIn not implemented")
}
func (UnimplementedGoto3Server) StreamOut(*StreamConfig, grpc.ServerStreamingServer[Output]) error {
	return status.Errorf(codes.Unimplemented, "method StreamOut not implemented")
}
func (UnimplementedGoto3Server) StreamInOut(grpc.BidiStreamingServer[StreamConfig, Output]) error {
	return status.Errorf(codes.Unimplemented, "method StreamInOut not implemented")
}
func (UnimplementedGoto3Server) mustEmbedUnimplementedGoto3Server() {}
func (UnimplementedGoto3Server) testEmbeddedByValue()               {}

// UnsafeGoto3Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Goto3Server will
// result in compilation errors.
type UnsafeGoto3Server interface {
	mustEmbedUnimplementedGoto3Server()
}

func RegisterGoto3Server(s grpc.ServiceRegistrar, srv Goto3Server) {
	// If the following call pancis, it indicates UnimplementedGoto3Server was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Goto3_ServiceDesc, srv)
}

func _Goto3_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Input)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Goto3Server).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Goto3_Echo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Goto3Server).Echo(ctx, req.(*Input))
	}
	return interceptor(ctx, in, info, handler)
}

func _Goto3_StreamIn_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(Goto3Server).StreamIn(&grpc.GenericServerStream[Input, Output]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Goto3_StreamInServer = grpc.ClientStreamingServer[Input, Output]

func _Goto3_StreamOut_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamConfig)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(Goto3Server).StreamOut(m, &grpc.GenericServerStream[StreamConfig, Output]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Goto3_StreamOutServer = grpc.ServerStreamingServer[Output]

func _Goto3_StreamInOut_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(Goto3Server).StreamInOut(&grpc.GenericServerStream[StreamConfig, Output]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Goto3_StreamInOutServer = grpc.BidiStreamingServer[StreamConfig, Output]

// Goto3_ServiceDesc is the grpc.ServiceDesc for Goto3 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Goto3_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Goto3",
	HandlerType: (*Goto3Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "echo",
			Handler:    _Goto3_Echo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "streamIn",
			Handler:       _Goto3_StreamIn_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "streamOut",
			Handler:       _Goto3_StreamOut_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "streamInOut",
			Handler:       _Goto3_StreamInOut_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "goto.proto",
}
