//*
// Copyright 2025 uk
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: grpc.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	Goto_Echo_FullMethodName        = "/Goto/echo"
	Goto_StreamOut_FullMethodName   = "/Goto/streamOut"
	Goto_StreamInOut_FullMethodName = "/Goto/streamInOut"
)

// GotoClient is the client API for Goto service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GotoClient interface {
	Echo(ctx context.Context, in *Input, opts ...grpc.CallOption) (*Output, error)
	StreamOut(ctx context.Context, in *StreamConfig, opts ...grpc.CallOption) (Goto_StreamOutClient, error)
	StreamInOut(ctx context.Context, opts ...grpc.CallOption) (Goto_StreamInOutClient, error)
}

type gotoClient struct {
	cc grpc.ClientConnInterface
}

func NewGotoClient(cc grpc.ClientConnInterface) GotoClient {
	return &gotoClient{cc}
}

func (c *gotoClient) Echo(ctx context.Context, in *Input, opts ...grpc.CallOption) (*Output, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Output)
	err := c.cc.Invoke(ctx, Goto_Echo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gotoClient) StreamOut(ctx context.Context, in *StreamConfig, opts ...grpc.CallOption) (Goto_StreamOutClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Goto_ServiceDesc.Streams[0], Goto_StreamOut_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &gotoStreamOutClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Goto_StreamOutClient interface {
	Recv() (*Output, error)
	grpc.ClientStream
}

type gotoStreamOutClient struct {
	grpc.ClientStream
}

func (x *gotoStreamOutClient) Recv() (*Output, error) {
	m := new(Output)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *gotoClient) StreamInOut(ctx context.Context, opts ...grpc.CallOption) (Goto_StreamInOutClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Goto_ServiceDesc.Streams[1], Goto_StreamInOut_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &gotoStreamInOutClient{ClientStream: stream}
	return x, nil
}

type Goto_StreamInOutClient interface {
	Send(*StreamConfig) error
	Recv() (*Output, error)
	grpc.ClientStream
}

type gotoStreamInOutClient struct {
	grpc.ClientStream
}

func (x *gotoStreamInOutClient) Send(m *StreamConfig) error {
	return x.ClientStream.SendMsg(m)
}

func (x *gotoStreamInOutClient) Recv() (*Output, error) {
	m := new(Output)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GotoServer is the server API for Goto service.
// All implementations must embed UnimplementedGotoServer
// for forward compatibility
type GotoServer interface {
	Echo(context.Context, *Input) (*Output, error)
	StreamOut(*StreamConfig, Goto_StreamOutServer) error
	StreamInOut(Goto_StreamInOutServer) error
	mustEmbedUnimplementedGotoServer()
}

// UnimplementedGotoServer must be embedded to have forward compatible implementations.
type UnimplementedGotoServer struct {
}

func (UnimplementedGotoServer) Echo(context.Context, *Input) (*Output, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Echo not implemented")
}
func (UnimplementedGotoServer) StreamOut(*StreamConfig, Goto_StreamOutServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamOut not implemented")
}
func (UnimplementedGotoServer) StreamInOut(Goto_StreamInOutServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamInOut not implemented")
}
func (UnimplementedGotoServer) mustEmbedUnimplementedGotoServer() {}

// UnsafeGotoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GotoServer will
// result in compilation errors.
type UnsafeGotoServer interface {
	mustEmbedUnimplementedGotoServer()
}

func RegisterGotoServer(s grpc.ServiceRegistrar, srv GotoServer) {
	s.RegisterService(&Goto_ServiceDesc, srv)
}

func _Goto_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Input)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GotoServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Goto_Echo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GotoServer).Echo(ctx, req.(*Input))
	}
	return interceptor(ctx, in, info, handler)
}

func _Goto_StreamOut_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamConfig)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GotoServer).StreamOut(m, &gotoStreamOutServer{ServerStream: stream})
}

type Goto_StreamOutServer interface {
	Send(*Output) error
	grpc.ServerStream
}

type gotoStreamOutServer struct {
	grpc.ServerStream
}

func (x *gotoStreamOutServer) Send(m *Output) error {
	return x.ServerStream.SendMsg(m)
}

func _Goto_StreamInOut_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GotoServer).StreamInOut(&gotoStreamInOutServer{ServerStream: stream})
}

type Goto_StreamInOutServer interface {
	Send(*Output) error
	Recv() (*StreamConfig, error)
	grpc.ServerStream
}

type gotoStreamInOutServer struct {
	grpc.ServerStream
}

func (x *gotoStreamInOutServer) Send(m *Output) error {
	return x.ServerStream.SendMsg(m)
}

func (x *gotoStreamInOutServer) Recv() (*StreamConfig, error) {
	m := new(StreamConfig)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Goto_ServiceDesc is the grpc.ServiceDesc for Goto service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Goto_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Goto",
	HandlerType: (*GotoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "echo",
			Handler:    _Goto_Echo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "streamOut",
			Handler:       _Goto_StreamOut_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "streamInOut",
			Handler:       _Goto_StreamInOut_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "grpc.proto",
}
