//*
// Copyright 2025 uk
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: sample.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	SampleService_OneOne_FullMethodName   = "/SampleService/oneOne"
	SampleService_OneMany_FullMethodName  = "/SampleService/oneMany"
	SampleService_ManyOne_FullMethodName  = "/SampleService/manyOne"
	SampleService_ManyMany_FullMethodName = "/SampleService/manyMany"
)

// SampleServiceClient is the client API for SampleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SampleServiceClient interface {
	OneOne(ctx context.Context, in *SampleRequest, opts ...grpc.CallOption) (*SampleResponse, error)
	OneMany(ctx context.Context, in *SampleRequest, opts ...grpc.CallOption) (SampleService_OneManyClient, error)
	ManyOne(ctx context.Context, opts ...grpc.CallOption) (SampleService_ManyOneClient, error)
	ManyMany(ctx context.Context, opts ...grpc.CallOption) (SampleService_ManyManyClient, error)
}

type sampleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSampleServiceClient(cc grpc.ClientConnInterface) SampleServiceClient {
	return &sampleServiceClient{cc}
}

func (c *sampleServiceClient) OneOne(ctx context.Context, in *SampleRequest, opts ...grpc.CallOption) (*SampleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SampleResponse)
	err := c.cc.Invoke(ctx, SampleService_OneOne_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sampleServiceClient) OneMany(ctx context.Context, in *SampleRequest, opts ...grpc.CallOption) (SampleService_OneManyClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SampleService_ServiceDesc.Streams[0], SampleService_OneMany_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &sampleServiceOneManyClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SampleService_OneManyClient interface {
	Recv() (*SampleResponse, error)
	grpc.ClientStream
}

type sampleServiceOneManyClient struct {
	grpc.ClientStream
}

func (x *sampleServiceOneManyClient) Recv() (*SampleResponse, error) {
	m := new(SampleResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *sampleServiceClient) ManyOne(ctx context.Context, opts ...grpc.CallOption) (SampleService_ManyOneClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SampleService_ServiceDesc.Streams[1], SampleService_ManyOne_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &sampleServiceManyOneClient{ClientStream: stream}
	return x, nil
}

type SampleService_ManyOneClient interface {
	Send(*SampleRequest) error
	CloseAndRecv() (*SampleResponse, error)
	grpc.ClientStream
}

type sampleServiceManyOneClient struct {
	grpc.ClientStream
}

func (x *sampleServiceManyOneClient) Send(m *SampleRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *sampleServiceManyOneClient) CloseAndRecv() (*SampleResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(SampleResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *sampleServiceClient) ManyMany(ctx context.Context, opts ...grpc.CallOption) (SampleService_ManyManyClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SampleService_ServiceDesc.Streams[2], SampleService_ManyMany_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &sampleServiceManyManyClient{ClientStream: stream}
	return x, nil
}

type SampleService_ManyManyClient interface {
	Send(*SampleRequest) error
	Recv() (*SampleResponse, error)
	grpc.ClientStream
}

type sampleServiceManyManyClient struct {
	grpc.ClientStream
}

func (x *sampleServiceManyManyClient) Send(m *SampleRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *sampleServiceManyManyClient) Recv() (*SampleResponse, error) {
	m := new(SampleResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SampleServiceServer is the server API for SampleService service.
// All implementations must embed UnimplementedSampleServiceServer
// for forward compatibility
type SampleServiceServer interface {
	OneOne(context.Context, *SampleRequest) (*SampleResponse, error)
	OneMany(*SampleRequest, SampleService_OneManyServer) error
	ManyOne(SampleService_ManyOneServer) error
	ManyMany(SampleService_ManyManyServer) error
	mustEmbedUnimplementedSampleServiceServer()
}

// UnimplementedSampleServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSampleServiceServer struct {
}

func (UnimplementedSampleServiceServer) OneOne(context.Context, *SampleRequest) (*SampleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OneOne not implemented")
}
func (UnimplementedSampleServiceServer) OneMany(*SampleRequest, SampleService_OneManyServer) error {
	return status.Errorf(codes.Unimplemented, "method OneMany not implemented")
}
func (UnimplementedSampleServiceServer) ManyOne(SampleService_ManyOneServer) error {
	return status.Errorf(codes.Unimplemented, "method ManyOne not implemented")
}
func (UnimplementedSampleServiceServer) ManyMany(SampleService_ManyManyServer) error {
	return status.Errorf(codes.Unimplemented, "method ManyMany not implemented")
}
func (UnimplementedSampleServiceServer) mustEmbedUnimplementedSampleServiceServer() {}

// UnsafeSampleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SampleServiceServer will
// result in compilation errors.
type UnsafeSampleServiceServer interface {
	mustEmbedUnimplementedSampleServiceServer()
}

func RegisterSampleServiceServer(s grpc.ServiceRegistrar, srv SampleServiceServer) {
	s.RegisterService(&SampleService_ServiceDesc, srv)
}

func _SampleService_OneOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SampleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SampleServiceServer).OneOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SampleService_OneOne_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SampleServiceServer).OneOne(ctx, req.(*SampleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SampleService_OneMany_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SampleRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SampleServiceServer).OneMany(m, &sampleServiceOneManyServer{ServerStream: stream})
}

type SampleService_OneManyServer interface {
	Send(*SampleResponse) error
	grpc.ServerStream
}

type sampleServiceOneManyServer struct {
	grpc.ServerStream
}

func (x *sampleServiceOneManyServer) Send(m *SampleResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _SampleService_ManyOne_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SampleServiceServer).ManyOne(&sampleServiceManyOneServer{ServerStream: stream})
}

type SampleService_ManyOneServer interface {
	SendAndClose(*SampleResponse) error
	Recv() (*SampleRequest, error)
	grpc.ServerStream
}

type sampleServiceManyOneServer struct {
	grpc.ServerStream
}

func (x *sampleServiceManyOneServer) SendAndClose(m *SampleResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *sampleServiceManyOneServer) Recv() (*SampleRequest, error) {
	m := new(SampleRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _SampleService_ManyMany_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SampleServiceServer).ManyMany(&sampleServiceManyManyServer{ServerStream: stream})
}

type SampleService_ManyManyServer interface {
	Send(*SampleResponse) error
	Recv() (*SampleRequest, error)
	grpc.ServerStream
}

type sampleServiceManyManyServer struct {
	grpc.ServerStream
}

func (x *sampleServiceManyManyServer) Send(m *SampleResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *sampleServiceManyManyServer) Recv() (*SampleRequest, error) {
	m := new(SampleRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SampleService_ServiceDesc is the grpc.ServiceDesc for SampleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SampleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "SampleService",
	HandlerType: (*SampleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "oneOne",
			Handler:    _SampleService_OneOne_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "oneMany",
			Handler:       _SampleService_OneMany_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "manyOne",
			Handler:       _SampleService_ManyOne_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "manyMany",
			Handler:       _SampleService_ManyMany_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "sample.proto",
}
