package constants

const (
  HeaderViaGoto                   = "Via-Goto"
  HeaderGotoHost                  = "Goto-Host"
  HeaderGotoTunnelHost            = "Goto-Tunnel-Host"
  HeaderViaGotoTunnel             = "Via-Goto-Tunnel"
  HeaderGotoTunnel                = "Goto-Tunnel"
  HeaderGotoRequestedTunnel       = "Goto-Requested-Tunnel"
  HeaderGotoViaTunnelCount        = "Goto-Via-Tunnel-Count"
  HeaderGotoPort                  = "Goto-Port"
  HeaderGotoProtocol              = "Goto-Protocol"
  HeaderGotoRemoteAddress         = "Goto-Remote-Address"
  HeaderGotoResponseStatus        = "Goto-Response-Status"
  HeaderGotoResponseDelay         = "Goto-Response-Delay"
  HeaderGotoURIStatus             = "Goto-URI-Status"
  HeaderGotoURIStatusRemaining    = "Goto-URI-Status-Remaining"
  HeaderGotoRequestedStatus       = "Goto-Requested-Status"
  HeaderGotoForcedStatus          = "Goto-Forced-Status"
  HeaderGotoForcedStatusRemaining = "Goto-Forced-Status-Remaining"
  HeaderGotoStatusFlip            = "Goto-Status-Flip"
  HeaderGotoInAt                  = "Goto-In-At"
  HeaderGotoOutAt                 = "Goto-Out-At"
  HeaderGotoTook                  = "Goto-Took"
  HeaderFromGoto                  = "From-Goto"
  HeaderFromGotoHost              = "From-Goto-Host"
  HeaderGotoRequestID             = "Goto-Request-ID"
  HeaderGotoTargetID              = "Goto-Target-ID"
  HeaderGotoTargetURL             = "Goto-Target-URL"
  HeaderGotoRetryCount            = "Goto-Retry-Count"
  HeaderReadinessRequestCount     = "Readiness-Request-Count"
  HeaderReadinessOverflowCount    = "Readiness-Overflow-Count"
  HeaderLivenessRequestCount      = "Liveness-Request-Count"
  HeaderLivenessOverflowCount     = "Liveness-Overflow-Count"
  HeaderGotoFilteredRequest       = "Goto-Filtered-Request"

  HeaderContentType = "Content-Type"
  ContentTypeJSON   = "application/json"
  ContentTypeYAML   = "application/yaml"

  HeaderStoppingReadinessRequest = "Stopping-Readiness-Request"
)
